baseurl: "/"
title: "source{d}"

contentdir:   "hugo/content"
dataDir:      "hugo/data"
layoutdir:    "hugo/layouts"
themesdir:    "hugo/themes"
archetypedir: "hugo/archetype"
destination:  "public"
publishdir:   "public"
staticdir:    "static"
theme:        ""

metaDataFormat: "yaml"
uglyURLs: false
paginate: 10
paginatePath: "page"

googleAnalytics: ""

disableKinds:
    - RSS
    - Sitemap
enableRobotsTXT: true
enableEmoji: false

watch: true
log: false
verbose: false
verboseLog: false
cleanDestinationDir: true

taxonomies:
    category: "categories"
    class: "classes"

params:
    author: source{d}
    description: "source{d} aims to understand developers through their code. We analyze contributions from more than 7 million developers in the open source community."
    defaultemail: "hello@sourced.tech"
    location: "Madrid"
    favicon: "/img/logos/favicon.png"
    favicon96: "/img/logos/favicon96.png"
    pgpLink: "https://keybase.io/sourced"
    headerImageName: alan-turing
    social:
        twitter: "sourced"
        github: "src-d"
        linkedin: "sourced"
